require('plugins')
require('bindings')
require('opts')
require('ls')
require('cmp-conf')
require('colorscheme')
require('lualine-conf')
require('bufferline-conf')
require('explorer')
require('term')
require('treesitter-conf')
require('git')
require('indent')
require('zen')

